version: '3.8'
name: transcendence

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgress
    restart: always
    expose: 
      - "5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: "./backend/"
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./backend:/app
    depends_on:
      - "db"
  frontend:
    build:
      context: "./frontend/"
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  pgadmin:
    container_name: pgadmin42
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"

volumes:
  db_data:

networks:
  default:
    name: transcendence